# Generated by Django 3.2.5 on 2021-07-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_com',
            field=models.IntegerField(default=0, verbose_name='Род. комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Статья'),
        ),
    ]
